# -*- coding: utf-8 -*-
"""Array Manipulation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3bN-V-Vfhn0q4t72EeU4SVjzU5IcxUL
"""

def perform_operations(array_size, query_count, queries): #user-defined function
    arr = [0] * array_size

    for query in queries:
        start_index, end_index, value = query
        arr[start_index - 1:end_index] = [x + value for x in arr[start_index - 1:end_index]]
    return max(arr)


array_size_1 = int(input())
query_count_1 = int(input())
queries_1 = [list(map(int, input().split())) for _ in range(query_count_1)]

output_1 = perform_operations(array_size_1, query_count_1, queries_1)
print(output_1)