# -*- coding: utf-8 -*-
"""Clumsy Factorial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3bN-V-Vfhn0q4t72EeU4SVjzU5IcxUL
"""

def clumsy(n):
    if n == 1:
        return 1

    result = n * (n - 1) // (n - 2) + (n - 3)

    n -= 4
    while n >= 4:
        result -= n * (n - 1) // (n - 2) - (n - 3)
        n -= 4

    if n == 3:
        result -= 6
    elif n == 2:
        result -= 2
    elif n == 1:
        result -= 1

    return result

# Example usage:
n = int(input())
output = clumsy(n)
print(output)