# -*- coding: utf-8 -*-
"""Contiguous Array

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3bN-V-Vfhn0q4t72EeU4SVjzU5IcxUL
"""

def findMaxLength(nums):
    sum_map={0:-1}
    max_length=0
    running_sum=0

    for i in range (len(nums)):
        running_sum+=(1 if nums[i]==1 else -1)

        if running_sum in sum_map:
            max_length= max(max_length,i-sum_map[running_sum])
        else:
            sum_map[running_sum]=1
    return max_length

nums=[0,0,0,1,1,1]
print(findMaxLength(nums))