# -*- coding: utf-8 -*-
"""Maximize Number of Subsequences in a String

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3bN-V-Vfhn0q4t72EeU4SVjzU5IcxUL
"""

def maximumSubsequenceCount( text, pattern):
        res = cnt1 = cnt2 = 0
        for c in text:
            if c == pattern[1]:
                res += cnt1
                cnt2 += 1
            if c == pattern[0]:
                cnt1 += 1
        return res + max(cnt1, cnt2)



inputVal1 = input()
inputVal2 = input()
outputVal = maximumSubsequenceCount(inputVal1,inputVal2)
print(outputVal)