# -*- coding: utf-8 -*-
"""No Prefix set

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3bN-V-Vfhn0q4t72EeU4SVjzU5IcxUL
"""

def doSomething(passwords):#main funciton to check password
    for i in range(len(passwords)):#loop to iterate thorough the input
        for j in range(i + 1, len(passwords)):
            if passwords[i] == passwords[j] or passwords[i].startswith(passwords[j]) or passwords[j].startswith(passwords[i]):
                return "BAD PASSWORD"

    return "GOOD PASSWORD"

inputVal = input()
inputVal = inputVal.split(" ")
outputVal = doSomething(inputVal)
print(outputVal)