# -*- coding: utf-8 -*-
"""Query Kth Smallest Trimmed Number

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3bN-V-Vfhn0q4t72EeU4SVjzU5IcxUL
"""

def query_kth_smallest_trimmed_number(nums, queries):
    original_length = len(nums[0])
    answer = []

    for query in queries:
        position, trim_length = query

        # Trim each number to its rightmost trim_length digits
        trimmed_nums = [int(num[-trim_length:]) for num in nums]

        # Sort the trimmed numbers and get the index of the kth smallest trimmed number
        sorted_indices = sorted(range(len(trimmed_nums)), key=lambda k: (trimmed_nums[k], k))
        kth_smallest_index = sorted_indices[position - 1]

        # Reset each number to its original length
        nums = [str(num).zfill(original_length) for num in nums]

        # Store the answer for the current query
        answer.append(kth_smallest_index)

    return answer

nums_1 = input().split()
query_count_1 = int(input())
queries_1 = [tuple(map(int, input().split())) for _ in range(query_count_1)]
output_1 = query_kth_smallest_trimmed_number(nums_1, queries_1)
print(" ".join(map(str, output_1)))