# -*- coding: utf-8 -*-
"""Simple Text Editor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3bN-V-Vfhn0q4t72EeU4SVjzU5IcxUL
"""

class CustomStack:
    def __init__(self):
        self.text = ""
        self.stack = []

    def insert(self, value):
        self.text += value
        self.stack.append(("insert", len(value)))

    def delete(self, value):
        deleted_text = self.text[-value:]
        self.text = self.text[:-value]
        self.stack.append(("delete", deleted_text))

    def get(self, value):
        char_at_index = self.text[value - 1]
        print(char_at_index)

    def undo(self):
        if self.stack:
            last_command, last_value = self.stack.pop()
            if last_command == "insert":
                self.text = self.text[:-last_value]
            elif last_command == "delete":
                self.text += last_value

# Example usage for Exercise-1:
editor_1 = CustomStack()
commands_1 = ["1 abc", "3 3", "2 2", "3 1"]
for command in commands_1:
    cmd, *args = command.split()
    if cmd == "1":
        editor_1.insert(args[0])
    elif cmd == "2":
        editor_1.delete(int(args[0]))
    elif cmd == "3":
        editor_1.get(int(args[0]))

# Example usage for Exercise-2:
editor_2 = CustomStack()
commands_2 = ["1 zxy", "3 3", "2 2", "1 def", "3 2"]
for command in commands_2:
    cmd, *args = command.split()
    if cmd == "1":
        editor_2.insert(args[0])
    elif cmd == "2":
        editor_2.delete(int(args[0]))
    elif cmd == "3":
        editor_2.get(int(args[0]))

# Undo the last command in editor_2
editor_2.undo()