# -*- coding: utf-8 -*-
"""Sliding Subarray Beauty

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3bN-V-Vfhn0q4t72EeU4SVjzU5IcxUL
"""

def doSomething(arr,k,n):
    result = []
    left = right = 0
    while right + k - 1 < len(arr):
        subarray = arr[left:left + k]
        subarray.sort()
        smallest_nth = subarray[n - 1]
        print(smallest_nth, end=' ')
        left += 1
        right += 1

inputVal = list(map(int,input().strip().split()))
k= int(input())
n= int(input())
outputVal = doSomething(inputVal,k,n)