# -*- coding: utf-8 -*-
"""String Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3bN-V-Vfhn0q4t72EeU4SVjzU5IcxUL
"""

def analyze_email(email):
    total_chars=len(email)
    lowercase_count=sum(c.islower() for c in email)
    uppercase_count=sum(c.isupper() for c in email)
    digit_count=sum(c.isdigit() for c in email)
    other_count=total_chars-(lowercase_count+uppercase_count+digit_count)

    lowercase_percentage=round((lowercase_count/total_chars)*100,3)
    uppercase_percentage=round((uppercase_count/total_chars)*100,3)
    digit_percentage=round((digit_count/total_chars)*100,3)
    other_percentage=round((other_count/total_chars)*100,3)

    print(f"{uppercase_percentage}%")
    print(f"{lowercase_percentage}%")
    print(f"{digit_percentage}%")
    print(f"{other_percentage}%")

email_address="Support1@litwork.in"
result=analyze_email(email_address)