# -*- coding: utf-8 -*-
"""Sum of Numbers With Units Digit K

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3bN-V-Vfhn0q4t72EeU4SVjzU5IcxUL
"""

def doSomething(num,k):
    #Do Something
    num=int(num)
    k= int(k)
    if num==0:
        return 0
    for size in range(1,11):
        remainder = (k*size)%10
        if remainder == num%10 and size<=num// 10+1:
            return size
    return -1

num = input()
k= input()
outputVal = doSomething(num, k)
print (outputVal)